### PR TITLE
feat: ability to set the status configMap name

### PR DESCRIPTION
**Pull request by trutx**
This ports https://github.com/kubernetes/autoscaler/pull/3888 into the `v1.17.4` release

Also porting https://github.com/kubernetes/autoscaler/pull/3630 so two cluster-autoscaler instances don't collide in leader election context.

### CODE REVIEW

**Comment by trutx** [comment]
Also porting this PR https://github.com/kubernetes/autoscaler/pull/3940 to avoid what's below to happen on redeploys/pod restarts:
```
I0316 11:59:20.270592       1 main.go:371] Cluster Autoscaler 1.17.4
I0316 11:59:20.319842       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/cluster-autoscaler...
I0316 11:59:20.325219       1 leaderelection.go:352] lock is held by cluster-autoscaler-7655f578d-6x9b2 and has not yet expired
I0316 11:59:20.325239       1 leaderelection.go:247] failed to acquire lease kube-system/cluster-autoscaler
I0316 11:59:23.781962       1 leaderelection.go:352] lock is held by cluster-autoscaler-7655f578d-6x9b2 and has not yet expired
I0316 11:59:23.781977       1 leaderelection.go:247] failed to acquire lease kube-system/cluster-autoscaler
I0316 11:59:28.044788       1 leaderelection.go:352] lock is held by cluster-autoscaler-7655f578d-6x9b2 and has not yet expired
I0316 11:59:28.044803       1 leaderelection.go:247] failed to acquire lease kube-system/cluster-autoscaler
I0316 11:59:31.645043       1 leaderelection.go:352] lock is held by cluster-autoscaler-7655f578d-6x9b2 and has not yet expired
I0316 11:59:31.645059       1 leaderelection.go:247] failed to acquire lease kube-system/cluster-autoscaler
I0316 11:59:34.700998       1 leaderelection.go:352] lock is held by cluster-autoscaler-7655f578d-6x9b2 and has not yet expired
I0316 11:59:34.701012       1 leaderelection.go:247] failed to acquire lease kube-system/cluster-autoscaler
I0316 11:59:37.742850       1 leaderelection.go:252] successfully acquired lease kube-system/cluster-autoscaler
```

**Comment by idleyoungman** [comment]
Minor nit, doesn't need to block moving ahead: looks like the const for StatusConfigMapName is still there in `cluster-autoscaler/clusterstate/utils/status.go` but was removed in the upstream PR

**Review by idleyoungman — APPROVED** [review]
LGTM w/ the note about the unused const.

**Comment by trutx** [comment]
Good catch @idleyoungman, totally missed that one. Fixed.

**Review by idleyoungman — APPROVED** [review]

**Pull request merged**
